<?php
/**
 * @category     Inchoo
 * @package     Inchoo Featured Products
 * @author        Domagoj Potkoc, Inchoo Team <web@inchoo.net>
 * @modified    Mladen Lotar <mladen.lotar@surgeworks.com>, Vedran Subotic <vedran.subotic@surgeworks.com>
 */
?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="featured-products">
	<h1><?php echo $this->__($this->getBlockLabel()) ?></h1>
		<?php $i=0;$row=0; foreach ($_products->getItems() as $_product): ?>
					<div>
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-link">
							<img class="product-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135, 135) ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
						</a>
						<div class="product-description">
							<p class="name">
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>)">
									<?php echo $this->htmlEscape($_product->getName()) ?>
								</a>
							</p>
							<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
							<?php echo $this->getPriceHtml($_product, true, '-new') ?>

							<?php /* if($_product->isSaleable()): */ ?>
								<!-- <button type="button" class="button btn-cart" onclick="setLocation('<?php /* echo $this->getAddToCartUrl($_product) */ ?>')"><span><span><?php /* echo $this->__('Add to Cart') */ ?></span></span></button> -->
							<?php /* else: */ ?>
								<!-- <div class="out-of-stock"><?php /* echo $this->__('Out of stock') */ ?></div> -->
							<?php /* endif; */ ?>

						</div>
					</div>

			<?php $i++; if($i==$this->getItemsPerRow()):?>
				<?php $i=0;?>
			<?php endif;?>
		<?php endforeach; ?>
</div>
<?php endif; ?>