<?php
/**
 * Product:     Advanced Permissions v2.3.11
 * Package:     Aitoc_Aitpermissions_2.3.11_2.0.3_370531
 * Purchase ID: IdE1U6HnoZ1uVsL5XI63QxIw6UiCg3yWRooWxDrbgD
 * Generated:   2012-09-23 04:03:35
 * File path:   app/design/frontend/default/default/template/aitpermissions/lfooter.phtml
 * Copyright:   (c) 2012 AITOC, Inc.
 */
?>
<?php
/**
 * @copyright  Copyright (c) 2009 AITOC, Inc. 
 */
?>
<!-- ychrnilnvdsjiqsgbtonyscxmnlqbmiq -->