<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct()
?>
<?php if($_product->getResource()->getAttribute('faqs')->getFrontend()->getValue($_product) != ''): ?>
    <h2><?php echo $this->__('FAQs') ?></h2>
    <table id="faqs">
        <col width="25%" />
        <col />
        <tbody>
            <tr>
                <td class="data"><?php echo $_product->getResource()->getAttribute('faqs')->getFrontend()->getValue($_product) ?></td>
            </tr>
        </tbody>
    </table>
<?php endif;?>