<<style>
<!--
.imgwrap-layered-nav{

display: inline-block;
clear: none;
margin: -6px 3px;
background: url('http://proto.cobragolf.com/media/wysiwyg/temp/monaco.jpg');
width: 19px;
height: 19px;
}
-->
</style>
<?php
/**
 * @category    Bubble
 * @package     Bubble_AttributeOptionPro
 * @version     1.1.0
 * @copyright   Copyright (c) 2013 BubbleCode (http://shop.bubblecode.net)
 */
?>
<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */
?>
<?php if($this->canShowBlock()): ?>
    <div class="block block-layered-nav">
        <div class="block-title">
            <strong><span><?php echo $this->__('Shop By') ?></span></strong>
        </div>
        <div class="block-content">
            <?php echo $this->getStateHtml() ?>
            <?php if ($this->getLayer()->getState()->getFilters()): ?>
                <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
            <?php endif; ?>
            <?php if($this->canShowOptions()): ?>
                <p class="block-subtitle"><?php echo $this->__('Shopping Options') ?></p>
                <dl id="narrow-by-list">
                    <?php $_filters = $this->getFilters() ?>
                    <?php foreach ($_filters as $code => $_filter): ?>
                        <?php if($_filter->getItemsCount()): ?>
                            <?php if ($_filter->getAttributeModel() && $_img = $this->helper('bubble_aop')->getAttributeImage($_filter->getAttributeModel())): ?>
                                <dt style="background: none; padding-left: 4px; padding-bottom: 2px;">
                                    <div class="imgwrap-layered-nav " style="background:url('<?php echo $this->escapeHtml($_img); ?>')">
                                    </div>
                                    <span style="vertical-align: middle;"><?php echo $this->__($_filter->getName()) ?></span>
                                </dt>
                            <?php else: ?>
                                <dt><?php echo $this->__($_filter->getName()) ?></dt>
                            <?php endif; ?>
                            <dd><?php echo $_filter->getHtml() ?></dd>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </dl>
                <script type="text/javascript">decorateDataList('narrow-by-list')</script>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
