<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
/* @var $this Mage_Catalog_Block_Product_Compare_List */
?>
<?php
$venedor = $this->helper('venedor');
$b = $venedor->getConfigGroup();
?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Compare Products') ?></h1>
    <a href="#" onclick="window.print(); return false;" class="link-print"><?php echo $this->__('Print This Page') ?></a>
    <p class="desc clearfix"><?php echo $this->__('If after products comparing you find it hard to choose, you can write to our live support.') ?></p>
</div>
<?php $_total=$this->getItems()->getSize() ?>
<?php if($_total): 
$c = 0; $j = 1;
foreach($this->getItems() as $item):
    if ($c % 3 == 0) $items = array();
    $items[] = $item;
    if ($c % 3 == 2 || $c == $_total - 1) : ?>
    <table class="data-table compare-table" id="product_comparison-<?php echo $j ?>">
        <col width="26%" />
        <?php foreach($items as $_item): ?>
            <col width="<?php echo floor((100-26)/count($items)); ?>%" />
        <?php endforeach; ?>
        <tbody>
            <tr class="product-shop-row">
                <th><?php echo $this->__('Product Name') ?></th>
                <?php foreach($items as $_item): ?>
                <td>
                    <a class="product-image" href="<?php echo $this->getProductUrl($_item) ?>" title="<?php echo $this->stripTags($_item->getName(), null, true) ?>">
<?php
//Default image size
$imgWidth = 180;
$imgHeight = 180;

//Aspect Ratio
if ($b['product']['aspect_ratio'])
    $imgHeight = $imgWidth * $b['product']['image_ratio'];
?>
                        <img src="<?php echo $venedor->getImage($_item, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo $this->stripTags($_item->getName(), null, true) ?>" />
                    </a>
                    <h2 class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>" title="<?php echo $this->stripTags($_item->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?></a></h2>
                </td>
                <?php endforeach; ?>
            </tr>
            <tr class="product-shop-row">
                <th><?php echo $this->__('Price') ?></th>
                <?php foreach($items as $_item): ?>
                <td>
                    <?php echo $this->getPriceHtml($_item, true, '-compare-list-top') ?>
                </td>
            <?php endforeach; ?>
            </tr>
            <tr class="product-shop-row">
                <th><?php echo $this->__('Rating') ?></th>
                <?php foreach($items as $_item): ?>
                <td>
                    <?php $review = $this->getReviewsSummaryHtml($_item, 'short') ?>
                    <?php if ($review): ?>
                        <?php echo $review; ?>
                    <?php else: ?>
                        <div class="ratings">
                            <div class="rating-box">
                                <div class="rating" style="width:0"></div>
                            </div>
                            <span class="amount"><?php echo $this->__('No Review') ?></span>
                        </div>
                    <?php endif; ?>
                </td>
            <?php endforeach; ?>
            </tr>
            <tr class="product-shop-row">
                <th><?php echo $this->__('Availability') ?></th>
                <?php foreach($items as $_item): ?>
                <td>
                    <?php if($_item->isSaleable()): ?>
                        <p class="availability in-stock"><span><?php echo $this->__('In Stock') ?></span></p>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of Stock') ?></span></p>
                    <?php endif; ?>
                </td>
            <?php endforeach; ?>
            </tr>
        </tbody>
        <tbody>
        <?php foreach ($this->getAttributes() as $_attribute): ?>
            <tr>
                <th><span class="nobr"><?php echo $_attribute->getStoreLabel() ?></span></th>
                <?php foreach($items as $_item): ?>
                <td>
                    <?php switch ($_attribute->getAttributeCode()) {
                        case "price": ?>
                            <?php echo $this->getPriceHtml($_item, true, '-compare-list-' . $_attribute->getCode()) ?>
                            <?php break;
                        case "small_image": ?>
<?php
//Default image size
$imgWidth = 125;
$imgHeight = 125;

//Aspect Ratio
if ($b['product']['aspect_ratio'])
    $imgHeight = $imgWidth * $b['product']['image_ratio'];
?>
                            <img src="<?php echo $venedor->getImage($_item, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo $this->stripTags($_item->getName(), null, true) ?>" />
                            <?php break;
                        case "date":
                              echo substr($this->getProductAttributeValue($_item, $_attribute),0,10);
                              break;
                        default: ?>
                            <div class="std">
                                <?php echo $this->helper('catalog/output')->productAttribute($_item, $this->getProductAttributeValue($_item, $_attribute), $_attribute->getAttributeCode()) ?>
                            </div>
                            <?php break;
                    } ?>
                </td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
        <tbody>
            <tr class="add-to-row">
                <th>&nbsp;</th>
                <?php foreach($items as $_item): ?>
                <td>
                    <?php if($_item->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->helper('catalog/product_compare')->getAddToCartUrl($_item) ?>', true)"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <span class="availability out-of-stock"><span><?php echo $this->__('Out of Stock') ?></span></span>
                    <?php endif; ?>
                    <?php if ($b['product']['addlinks_wishlist'] && $this->helper('wishlist')->isAllow()) : ?>
                        <ul class="add-to-links">
                            <li><a href="<?php echo $this->getAddToWishlistUrl($_item);?>" class="link-wishlist button"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        </ul>
                    <?php endif; ?>
                    <br/>
                    <a href="#" class="button-arrow btn-remove" onclick="removeItem('<?php echo $this->helper('catalog/product_compare')->getRemoveUrl($_item) ?>');" title="<?php echo $this->__('Remove This Item') ?>"><?php echo $this->__('Remove This Item') ?></a>
                </td>
                <?php endforeach; ?>
            </tr>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('product_comparison-<?php echo $j++ ?>');</script>
<?php 
    endif;
    $c++;
endforeach; ?>


<?php
$c = 0; $j = 1;
foreach($this->getItems() as $item):
    if ($c % 2 == 0) $items = array();
    $items[] = $item;
    if ($c % 2 == 1 || $c == $_total - 1) : ?>
    <table class="data-table compare-table compare-table-mobile" id="product_comparison_mobile-<?php echo $j ?>">
    <?php foreach($items as $_item): ?>
        <col width="<?php echo floor(100/count($items)); ?>%" />
    <?php endforeach; ?>
        <tbody>
            <tr class="product-shop-row">
                <th colspan="<?php echo count($items) ?>"><?php echo $this->__('Product Name') ?></th>
            </tr>
            <tr class="product-shop-row">
            <?php foreach($items as $_item): ?>
                <td>
                    <a class="product-image" href="<?php echo $this->getProductUrl($_item) ?>" title="<?php echo $this->stripTags($_item->getName(), null, true) ?>">
<?php
//Default image size
$imgWidth = 180;
$imgHeight = 180;

//Aspect Ratio
if ($b['product']['aspect_ratio'])
    $imgHeight = $imgWidth * $b['product']['image_ratio'];
?>
                        <img src="<?php echo $venedor->getImage($_item, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo $this->stripTags($_item->getName(), null, true) ?>" />
                    </a>
                    <h2 class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>" title="<?php echo $this->stripTags($_item->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?></a></h2>
                </td>
            <?php endforeach; ?>
            </tr>
            <tr class="product-shop-row">
                <th colspan="<?php echo count($items); ?>"><?php echo $this->__('Price') ?></th>
            </tr>
            <tr class="product-shop-row">
            <?php foreach($items as $_item): ?>
                <td>
                    <?php echo $this->getPriceHtml($_item, true, '-compare-list-top') ?>
                </td>
            <?php endforeach; ?>
            </tr>
            <tr class="product-shop-row">
                <th colspan="<?php echo count($items) ?>"><?php echo $this->__('Rating') ?></th>
            </tr>
            <tr class="product-shop-row">
            <?php foreach($items as $_item): ?>
                <td>
                    <?php $review = $this->getReviewsSummaryHtml($_item, 'short') ?>
                    <?php if ($review): ?>
                        <?php echo $review; ?>
                    <?php else: ?>
                        <div class="ratings">
                            <div class="rating-box">
                                <div class="rating" style="width:0"></div>
                            </div>
                            <span class="amount"><?php echo $this->__('No Review') ?></span>
                        </div>
                    <?php endif; ?>
                </td>
            <?php endforeach; ?>
            </tr>
            <tr class="product-shop-row">
                <th colspan="<?php echo count($items) ?>"><?php echo $this->__('Availability') ?></th>
            </tr>
            <tr class="product-shop-row">
            <?php foreach($items as $_item): ?>
                <td>
                    <?php if($_item->isSaleable()): ?>
                        <p class="availability in-stock"><span><?php echo $this->__('In Stock') ?></span></p>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of Stock') ?></span></p>
                    <?php endif; ?>
                </td>
            <?php endforeach; ?>
            </tr>
        </tbody>
        <tbody>
        <?php foreach ($this->getAttributes() as $_attribute): ?>
            <tr>
                <th colspan="<?php echo count($items) ?>"><span class="nobr"><?php echo $_attribute->getStoreLabel() ?></span></th>
            </tr>
            <tr>
            <?php foreach($items as $_item): ?>
                <td>
                    <?php switch ($_attribute->getAttributeCode()) {
                        case "price": ?>
                            <?php echo $this->getPriceHtml($_item, true, '-compare-list-' . $_attribute->getCode()) ?>
                            <?php break;
                        case "small_image": ?>
<?php
//Default image size
$imgWidth = 125;
$imgHeight = 125;

//Aspect Ratio
if ($b['product']['aspect_ratio'])
    $imgHeight = $imgWidth * $b['product']['image_ratio'];
?>
                            <img src="<?php echo $venedor->getImage($_item, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo $this->stripTags($_item->getName(), null, true) ?>" />
                            <?php break;
                        case "date":
                              echo substr($this->getProductAttributeValue($_item, $_attribute),0,10);
                              break;
                        default: ?>
                            <div class="std">
                                <?php echo $this->helper('catalog/output')->productAttribute($_item, $this->getProductAttributeValue($_item, $_attribute), $_attribute->getAttributeCode()) ?>
                            </div>
                            <?php break;
                    } ?>
                </td>
            <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
        <tbody>
            <tr class="add-to-row">
                <?php foreach($items as $_item): ?>
                <td>
                    <?php if($_item->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->helper('catalog/product_compare')->getAddToCartUrl($_item) ?>', true)"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <span class="availability out-of-stock"><span><?php echo $this->__('Out of Stock') ?></span></span>
                    <?php endif; ?>
                    <?php if ($b['product']['addlinks_wishlist'] && $this->helper('wishlist')->isAllow()) : ?>
                        <ul class="add-to-links">
                            <li><a href="<?php echo $this->getAddToWishlistUrl($_item);?>" class="link-wishlist button"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        </ul>
                    <?php endif; ?>
                    <br/>
                    <a href="#" class="button-arrow btn-remove" onclick="removeItem('<?php echo $this->helper('catalog/product_compare')->getRemoveUrl($_item) ?>');" title="<?php echo $this->__('Remove This Item') ?>"><?php echo $this->__('Remove This Item') ?></a>
                </td>
                <?php endforeach; ?>
            </tr>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('product_comparison_mobile-<?php echo $j++ ?>');</script>
<?php 
    endif;
    $c++;
endforeach; ?>
    <script type="text/javascript">
        /**
         * Send remove item request, after that reload windows
         */
        function removeItem(url)
        {
            new Ajax.Request(url, {
                parameters: {isAjax: 1, method: 'POST'},
                onLoading: function(){$('compare-list-please-wait').show();},
                onSuccess: function(transport) {
                    $('compare-list-please-wait').hide();
                    window.location.reload();
                    window.opener.location.reload();
                }
            });
        }
    </script>
<?php endif; ?>
