<?php 
/**
 * Store switcher template
 *
 * @see Mage_Core_Block_Store_Switcher
 */
?>
<?php if(count($this->getGroups())>1): ?>
<div class="block store-switcher">
    <div class="block-title">
        <span><?php echo $this->__('Select Store') ?></span>
    </div>
    <div class="block-content dropdown">
        <a href="#" class="button dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="false" title="<?php echo $this->__('Select Store') ?>">
            <?php foreach ($this->getGroups() as $_group): ?>
                <?php if ($_group->getId() == $this->getCurrentGroupId()): ?>
                    <span class="name"><?php echo $this->htmlEscape($_group->getName()) ?></span>
                <?php endif; ?>
            <?php endforeach; ?>
        </a>
        <ul class="dropdown-menu">
            <?php foreach ($this->getGroups() as $_group): ?>
                <?php if ($_group->getId() != $this->getCurrentGroupId()): ?>
                    <li><a tabindex="-1" href="<?php echo $_group->getHomeUrl() ?>"><?php echo $this->htmlEscape($_group->getName()) ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>            
        </ul>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
jQuery(function($) {
    var venedor_store_timer;
    
    function venedor_resize_store() {
        var w1 = $('.store-switcher .dropdown-toggle').css('width','auto').innerWidth() + 1;
        var w2 = $('.store-switcher .dropdown-menu').css('width','auto').innerWidth() + 1;
        if (w1 > w2) {
            $('.store-switcher .dropdown-toggle').css('width', w1 + 'px');
            $('.store-switcher .dropdown-menu').css('width', w1 + 'px');
        } else {
            $('.store-switcher .dropdown-toggle').css('width', w2 + 'px');
            $('.store-switcher .dropdown-menu').css('width', w2 + 'px');
        }
        if (venedor_store_timer) clearTimeout(venedor_store_timer); 
    }
    
    $(window).resize(function() {
        clearTimeout(venedor_store_timer); 
        venedor_store_timer = setTimeout(venedor_resize_store, 100); 
    });
    venedor_resize_store();
});
//]]>
</script>
<?php endif; ?>
