<?php
/**
 * Coupons.php
 *
 * @category    Tegdesign
 * @package     Emailcollector
 * @author      Tegan Snyder <tsnyder@tegdesign.com>
 *
 */
class Tegdesign_Emailcollector_Model_System_Config_Source_Coupons extends Mage_Core_Model_Abstract
{

    public function toOptionArray()
    {

        $collection = Mage::getModel('salesrule/rule')->getCollection();
		$options = array();

		$x = 0;
		foreach ($collection as $rule) {

			$code = $rule->getCode();
			$name = $rule->getName();

			if (!empty($code)) {

				if (strpos($name, 'email collector popup coupon') !== false) {

					// hide all the coupons that where auto generated by this
					// extension so we dont muck this up

				} else {

			        $options[$x]['value'] = $code;
		        	$options[$x]['label'] = $code;

			        $x = $x + 1;

		    	}

	    	}

        }

    	return $options;

    }

}