<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
$venedor = $this->helper('venedor');
$rowClass = $venedor->getRowClass();
$spanClass = $venedor->getSpanClass();
$b = $venedor->getConfigGroup();

$_productCollection=$this->getLoadedProductCollection();
$_uid = $this->getFrontHash();

$_helper = $this->helper('catalog/output');

//Default image size
$imgWidth = 228;
$imgHeight = 228;

//Aspect Ratio
if ($b['product']['aspect_ratio'])
    $imgHeight = $imgWidth * $b['product']['image_ratio'];

$blockName = $this->getBlockName();
$blockDescription = $this->getBlockDescription();
$blockId = $this->getFrontHash();
?>
<div class="featured-products">
    <?php if ($blockName) : ?><h2 class="subtitle"><span class="inline-title"><?php echo $this->__($blockName);; ?></span><?php if ($_productCollection->count() > 2) echo '<div class="line"></div>'; ?></h2><?php endif; ?>
    <?php if ($blockDescription) : ?><p class="desc"><?php echo $this->getBlockDescription() ?></p><?php endif; ?>
    <?php if(!$_productCollection->count()): ?>
        <p class="note-msg"><?php echo $this->__('There are no products.') ?></p>
    <?php else: ?>
        <div id="featured-products-list-<?php echo $blockId ?>" class="products-grid flexslider large-icons"><ul class="slides">
        <?php foreach ($_productCollection as $_product): ?>
            <li class="item<?php if (!$b['category']['grid_effect']) echo ' hover-disable' ?><?php if (!$b['category']['grid_addliks_inline']) echo ' addlinks-block' ?>"><div class="item-inner">
                <div class="product-image">
                    <?php 
                    if ($b['category']['hover_image'])
                        $hoverImgHtml = $venedor->getHoverImageHtml($_product, $imgWidth, $imgHeight); 
                    ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">
                        <img<?php if ($hoverImgHtml) echo ' class="primary-image"'; ?> src="<?php echo $venedor->getImage($_product, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                        <?php echo $hoverImgHtml; ?>
                        <?php 
                        $labels_tl = ''; $labels_tr = ''; $labels_bl = ''; $labels_br = '';
                        $new_html = '';
                        if ($b['product']['new_label']) {
                            // New Product 
                            $newsFromDate = $_product->getNewsFromDate();
                            $newsToDate = $_product->getNewsToDate();
                            $new_html = '';
                            if ($newsFromDate && $newsToDate && Mage::app()->getLocale()->IsStoreDateInInterval(Mage::app()->getStore(), $newsFromDate, $newsToDate))
                                $new_html = '<div class="new ' . $b['product']['new_label_type'] . '">'. $this->__('New') .'</div>';
                            switch ($b['product']['new_label_pos']) {
                                case 'top-right': $labels_tr .= $new_html; break;
                                case 'bottom-left': $labels_bl .= $new_html; break;
                                case 'bottom-right': $labels_br .= $new_html; break;
                                default: $labels_tl .= $new_html; break;
                            }
                        }
                        if ($b['product']['sale_label']) {
                            // Special Product
                            $specialPriceFromDate = $_product->getSpecialFromDate();
                            $specialPriceToDate = $_product->getSpecialToDate();
                            $sales_html = '';
                            if ($specialPriceFromDate && $specialPriceToDate && Mage::app()->getLocale()->isStoreDateInInterval(Mage::app()->getStore(), $specialPriceFromDate, $specialPriceToDate)) {
                                $price = $_product->getPrice();
                                $specialprice = $_product->getSpecialPrice();
                                $sales_html = '<div class="sales ' . $b['product']['sale_label_type'] . '">' . round(($specialprice - $price) / $price * 100) . '%</div>';
                            }
                            switch ($b['product']['sale_label_pos']) {
                                case 'top-right': $labels_tr .= $sales_html; break;
                                case 'bottom-left': $labels_bl .= $sales_html; break;
                                case 'bottom-right': $labels_br .= $sales_html; break;
                                default: $labels_tl .= $sales_html; break;
                            }
                        }
                        if ($labels_tl) echo '<div class="labels top-left">' . $labels_tl . '</div>';
                        if ($labels_tr) echo '<div class="labels top-right">' . $labels_tr . '</div>';
                        if ($labels_bl) echo '<div class="labels bottom-left">' . $labels_bl . '</div>';
                        if ($labels_br) echo '<div class="labels bottom-right">' . $labels_br . '</div>';
                        ?>
                    </a>
                    <?php if ($b['product']['price_on_image']) : ?>
                        <?php echo $this->getPriceHtml($_product, true, '-featured-slider') ?>
                    <?php endif; ?>
                </div>
                <?php // Product description ?>
                <div class="product-shop">
                    <?php if (!$b['product']['price_on_image']) : ?>
                    <div class="price-review">
                        <?php echo $this->getPriceHtml($_product, true, '-featured-slider') ?>
                    <?php endif; ?>
                    
                    <div class="reviews-wrap">
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    </div>
                    <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h3>
                    <div class="actions clearfix">
                        <?php if($_product->isSaleable()): ?>
                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php else: ?>
                            <span class="availability out-of-stock"><span><?php echo $this->__('Out of Stock') ?></span></span>
                        <?php endif; ?>
                        <?php if (($b['product']['addlinks_wishlist'] && $this->helper('wishlist')->isAllow()) || ($b['product']['addlinks_compare'] && $this->getAddToCompareUrl($_product))) : ?>
                        <span class="add-to-links">
                            <?php if ($b['product']['addlinks_wishlist'] && $this->helper('wishlist')->isAllow()) : ?>
                                <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="button link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><?php echo $this->__('Add to Wishlist') ?></a>
                            <?php endif; ?>
                            <?php if($b['product']['addlinks_compare'] && $_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <a href="<?php echo $_compareUrl ?>" class="button link-compare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a>
                            <?php endif; ?>
                        </span>
                        <?php endif; ?>
                    </div>
                    
                    <?php if (!$b['product']['price_on_image']) : ?></div><?php endif; ?>
                </div>
            </div></li>
        <?php endforeach; ?>
        </ul></div>
        <script type="text/javascript">decorateList('feaduterd-products-list-<?php echo $blockId ?>', 'none-recursive')</script>
        <?php $isWideSlider = $this->getIsWide(); ?>
        <script type="text/javascript">
        //<![CDATA[
        jQuery(function($) {
            var bp = 963;
            if ($('body').hasClass('bv3'))
                bp = 975;
            $('#featured-products-list-<?php echo $blockId ?>').flexslider({
                controlNav: false,
                animation: 'slide',
                animationLoop: false,
                <?php if ($isWideSlider) : ?>
                minItems: 4,
                maxItems: 4,
                <?php else : ?>
                minItems: 3,
                maxItems: 3,
                <?php endif; ?>
                itemWidth: 228
            })
            <?php if ($isWideSlider) : ?>
            .data("break_default", [4, 228])
            <?php else : ?>
            .data("break_default", [3, 228])
            <?php endif; ?>
            <?php if ($isWideSlider) : ?>
            .data("break_points", [ [bp, 3, 190], [750, 2, 190], [530, 1, 228] ] );
            <?php else : ?>
            .data("break_points", [ [bp, 2, 190], [750, 2, 190], [530, 1, 228] ] );
            <?php endif; ?>
        });
        //]]>
        </script>
    <?php endif; ?>
</div>
