<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php 
$venedor = $this->helper('venedor');
$b = $venedor->getConfigGroup();

//Default image size
$imgWidth = 100;
$imgHeight = 100;

//Aspect Ratio
if ($b['product']['aspect_ratio'])
    $imgHeight = $imgWidth * $b['product']['image_ratio'];
    

if($this->getItems()->getSize()): ?>
<div class="block block-list block-related">
    <div class="block-title">
        <strong><span><?php echo $this->__('Optional Accessories') ?></span></strong>
    </div>
    <div class="block-content">
        <p class="block-subtitle"><?php echo $this->__('Check items to add to the cart or') ?>&nbsp;<a href="#" onclick="selectAllRelated(this); return false;"><?php echo $this->__('select all') ?></a></p>
        <div id="block-related" class="mini-products-list flexslider">
	        <ul class="slides">
	        <?php
	        $i = 0; foreach($this->getItems() as $_item): ?>
	            <li>
		            <div class="item clearfix">
		                <?php if(!$_item->isComposite() && $_item->isSaleable()): ?>
		                    <?php if (!$_item->getRequiredOptions()): ?>
		                        <input type="checkbox" class="checkbox related-checkbox" id="related-checkbox<?php echo $_item->getId() ?>" name="related_products[]" value="<?php echo $_item->getId() ?>" />
		                    <?php endif; ?>
		                <?php endif; ?>
		                <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image">
		                    <img src="<?php echo $venedor->getImage($_item, $imgWidth, $imgHeight, 'thumbnail'); ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" />
		                </a>
		                <div class="product-details">
		                    <p class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></p>
		                    <?php echo $this->getPriceHtml($_item, true, '-related') ?>
		                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
		                        <a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-add"><?php echo $this->__('Add to Wishlist') ?></a>
		                    <?php endif; ?>
		                </div>
		            </div>
	            </li>
	        <?php $i++; endforeach ?>
	        </ul>
        </div>
        <script type="text/javascript">decorateList('block-related', 'none-recursive')</script>
        <script type="text/javascript">
        //<![CDATA[
            jQuery(function($) {
                $('#block-related').flexslider({
                    controlNav: false,
                    animation: 'slide',
                    smoothHeight: true
                });
            });
        //]]>
        </script>
    </div>
    <script type="text/javascript">
    //<![CDATA[
    $$('.related-checkbox').each(function(elem){
        Event.observe(elem, 'click', addRelatedToProduct)
    });

    var relatedProductsCheckFlag = false;
    function selectAllRelated(txt){
        if (relatedProductsCheckFlag == false) {
            $$('.related-checkbox').each(function(elem){
                elem.checked = true;
            });
            relatedProductsCheckFlag = true;
            txt.innerHTML="<?php echo $this->__('unselect all') ?>";
        } else {
            $$('.related-checkbox').each(function(elem){
                elem.checked = false;
            });
            relatedProductsCheckFlag = false;
            txt.innerHTML="<?php echo $this->__('select all') ?>";
        }
        addRelatedToProduct();
    }

    function addRelatedToProduct(){
        var checkboxes = $$('.related-checkbox');
        var values = [];
        for(var i=0;i<checkboxes.length;i++){
            if(checkboxes[i].checked) values.push(checkboxes[i].value);
        }
        if($('related-products-field')){
            $('related-products-field').value = values.join(',');
        }
    }
    //]]>
    </script>
</div>
<?php endif ?>
