
(function(){if(window.magicJS){return}
var a={version:"v2.4.1",UUID:0,storage:{},$uuid:function(b){return(b.$J_UUID||(b.$J_UUID=++$J.UUID))},getStorage:function(b){return($J.storage[b]||($J.storage[b]={}))},$F:function(){},$false:function(){return false},defined:function(b){return(undefined!=b)},exists:function(b){return!!(b)},j1:function(b){if(!$J.defined(b)){return false}
if(b.$J_TYPE){return b.$J_TYPE}
if(!!b.nodeType){if(1==b.nodeType){return"element"}
if(3==b.nodeType){return"textnode"}}
if(b.length&&b.item){return"collection"}
if(b.length&&b.callee){return"arguments"}
if((b instanceof window.Object||b instanceof window.Function)&&b.constructor===$J.Class){return"class"}
if(b instanceof window.Array){return"array"}
if(b instanceof window.Function){return"function"}
if(b instanceof window.String){return"string"}
if($J.j21.trident){if($J.defined(b.cancelBubble)){return"event"}}else{if(b instanceof window.Event||b===window.event||b.constructor==window.MouseEvent){return"event"}}
if(b instanceof window.Date){return"date"}
if(b instanceof window.RegExp){return"regexp"}
if(b===window){return"window"}
if(b===document){return"document"}
return typeof(b)},extend:function(g,f){if(!(g instanceof window.Array)){g=[g]}
for(var e=0,c=g.length;e<c;e++){if(!$J.defined(g)){continue}
for(var d in(f||{})){try{g[e][d]=f[d]}catch(b){}}}
return g[0]},implement:function(f,e){if(!(f instanceof window.Array)){f=[f]}
for(var d=0,b=f.length;d<b;d++){if(!$J.defined(f[d])){continue}
if(!f[d].prototype){continue}
for(var c in(e||{})){if(!f[d].prototype[c]){f[d].prototype[c]=e[c]}}}
return f[0]},nativize:function(d,c){if(!$J.defined(d)){return d}
for(var b in(c||{})){if(!d[b]){d[b]=c[b]}}
return d},$try:function(){for(var c=0,b=arguments.length;c<b;c++){try{return arguments[c]()}catch(d){}}
return null},$A:function(d){if(!$J.defined(d)){return $mjs([])}
if(d.toArray){return $mjs(d.toArray())}
if(d.item){var c=d.length||0,b=new Array(c);while(c--){b[c]=d[c]}
return $mjs(b)}
return $mjs(Array.prototype.slice.call(d))},now:function(){return new Date().getTime()},detach:function(f){var d;switch($J.j1(f)){case"object":d={};for(var e in f){d[e]=$J.detach(f[e])}
break;case"array":d=[];for(var c=0,b=f.length;c<b;c++){d[c]=$J.detach(f[c])}
break;default:return f}
return $J.$(d)},$:function(c){if(!$J.defined(c)){return null}
if(c.$J_EXTENDED){return c}
switch($J.j1(c)){case"array":c=$J.nativize(c,$J.extend($J.Array,{$J_EXTENDED:$J.$F}));c.j14=c.forEach;return c;break;case"string":var b=document.getElementById(c);if($J.defined(b)){return $J.$(b)}
return null;break;case"window":case"document":$J.$uuid(c);c=$J.extend(c,$J.Doc);break;case"element":$J.$uuid(c);c=$J.extend(c,$J.Element);break;case"event":c=$J.extend(c,$J.Event);break;case"textnode":return c;break;case"function":case"array":case"date":default:break}
return $J.extend(c,{$J_EXTENDED:$J.$F})},$new:function(b,d,c){return $mjs($J.doc.createElement(b)).setProps(d||{}).j6(c||{})}};window.magicJS=window.$J=a;window.$mjs=a.$;$J.Array={$J_TYPE:"array",indexOf:function(e,f){var b=this.length;for(var c=this.length,d=(f<0)?Math.max(0,c+f):f||0;d<c;d++){if(this[d]===e){return d}}
return-1},contains:function(b,c){return this.indexOf(b,c)!=-1},forEach:function(b,e){for(var d=0,c=this.length;d<c;d++){if(d in this){b.call(e,this[d],d,this)}}},filter:function(b,g){var f=[];for(var e=0,c=this.length;e<c;e++){if(e in this){var d=this[e];if(b.call(g,this[e],e,this)){f.push(d)}}}
return f},map:function(b,f){var e=[];for(var d=0,c=this.length;d<c;d++){if(d in this){e[d]=b.call(f,this[d],d,this)}}
return e}};$J.implement(String,{$J_TYPE:"string",j26:function(){return this.replace(/^\s+|\s+$/g,"")},trimLeft:function(){return this.replace(/^\s+/g,"")},trimRight:function(){return this.replace(/\s+$/g,"")},j25:function(b){return(this.toString()===b.toString())},icompare:function(b){return(this.toLowerCase().toString()===b.toLowerCase().toString())},j22:function(){return this.replace(/-\D/g,function(b){return b.charAt(1).toUpperCase()})},dashize:function(){return this.replace(/[A-Z]/g,function(b){return("-"+b.charAt(0).toLowerCase())})},j17:function(c){return parseInt(this,c||10)},toFloat:function(){return parseFloat(this)},j18:function(){return!this.replace(/true/i,"").j26()},has:function(c,b){b=b||"";return(b+this+b).indexOf(b+c+b)>-1}});a.implement(Function,{$J_TYPE:"function",j24:function(){var c=$J.$A(arguments),b=this,d=c.shift();return function(){return b.apply(d||null,c.concat($J.$A(arguments)))}},j16:function(){var c=$J.$A(arguments),b=this,d=c.shift();return function(e){return b.apply(d||null,$mjs([e||window.event]).concat(c))}},j27:function(){var c=$J.$A(arguments),b=this,d=c.shift();return window.setTimeout(function(){return b.apply(b,c)},d||0)},j28:function(){var c=$J.$A(arguments),b=this;return function(){return b.j27.apply(b,c)}},interval:function(){var c=$J.$A(arguments),b=this,d=c.shift();return window.setInterval(function(){return b.apply(b,c)},d||0)}});$J.j21={features:{xpath:!!(document.evaluate),air:!!(window.runtime),query:!!(document.querySelector)},engine:(window.opera)?"presto":!!(window.ActiveXObject)?"trident":(!navigator.taintEnabled)?"webkit":(undefined!=document.getBoxObjectFor||null!=window.mozInnerScreenY)?"gecko":"unknown",version:"",platform:($J.defined(window.orientation))?"ipod":(navigator.platform.match(/mac|win|linux/i)||["other"])[0].toLowerCase(),backCompat:document.compatMode&&"backcompat"==document.compatMode.toLowerCase(),getDoc:function(){return(document.compatMode&&"backcompat"==document.compatMode.toLowerCase())?document.body:document.documentElement},ready:false,onready:function(){if($J.j21.ready){return}
$J.j21.ready=true;$J.body=$mjs(document.body);$mjs(document).raiseEvent("domready")}};(function(){function b(){return!!(arguments.callee.caller)}
$J.j21.version=("presto"==$J.j21.engine)?!!(document.head)?270:!!(window.applicationCache)?260:!!(window.localStorage)?250:($J.j21.features.query)?220:((b())?211:((document.getElementsByClassName)?210:200)):("trident"==$J.j21.engine)?!!(window.msPerformance||window.performance)?900:!!(window.XMLHttpRequest&&window.postMessage)?6:((window.XMLHttpRequest)?5:4):("webkit"==$J.j21.engine)?(($J.j21.features.xpath)?(($J.j21.features.query)?525:420):419):("gecko"==$J.j21.engine)?!!(document.head)?200:!!document.readyState?192:!!(window.localStorage)?191:((document.getElementsByClassName)?190:181):"";$J.j21[$J.j21.engine]=$J.j21[$J.j21.engine+$J.j21.version]=true;if(window.chrome){$J.j21.chrome=true}})();$J.Element={j13:function(b){return this.className.has(b," ")},j2:function(b){if(b&&!this.j13(b)){this.className+=(this.className?" ":"")+b}
return this},j3:function(b){b=b||".*";this.className=this.className.replace(new RegExp("(^|\\s)"+b+"(?:\\s|$)"),"$1").j26();return this},j4:function(b){return this.j13(b)?this.j3(b):this.j2(b)},j5:function(c){c=(c=="float"&&this.currentStyle)?"styleFloat":c.j22();var b=null;if(this.currentStyle){b=this.currentStyle[c]}else{if(document.defaultView&&document.defaultView.getComputedStyle){css=document.defaultView.getComputedStyle(this,null);b=css?css.getPropertyValue([c.dashize()]):null}}
if(!b){b=this.style[c]}
if("opacity"==c){return $J.defined(b)?parseFloat(b):1}
if(/^(border(Top|Bottom|Left|Right)Width)|((padding|margin)(Top|Bottom|Left|Right))$/.test(c)){b=parseInt(b)?b:"0px"}
return("auto"==b?null:b)},j6Prop:function(c,b){try{if("opacity"==c){this.j23(b);return this}
if("float"==c){this.style[("undefined"===typeof(this.style.styleFloat))?"cssFloat":"styleFloat"]=b;return this}
this.style[c.j22()]=b+(("number"==$J.j1(b)&&!$mjs(["zIndex","zoom"]).contains(c.j22()))?"px":"")}catch(d){}
return this},j6:function(c){for(var b in c){this.j6Prop(b,c[b])}
return this},j19s:function(){var b={};$J.$A(arguments).j14(function(c){b[c]=this.j5(c)},this);return b},j23:function(e,c){c=c||false;e=parseFloat(e);if(c){if(e==0){if("hidden"!=this.style.visibility){this.style.visibility="hidden"}}else{if("visible"!=this.style.visibility){this.style.visibility="visible"}}}
if($J.j21.trident){if(!this.currentStyle||!this.currentStyle.hasLayout){this.style.zoom=1}
try{var d=this.filters.item("DXImageTransform.Microsoft.Alpha");d.enabled=(1!=e);d.opacity=e*100}catch(b){this.style.filter+=(1==e)?"":"progid:DXImageTransform.Microsoft.Alpha(enabled=true,opacity="+e*100+")"}}
this.style.opacity=e;return this},setProps:function(b){for(var c in b){this.setAttribute(c,""+b[c])}
return this},hide:function(){return this.j6({display:"none",visibility:"hidden"})},show:function(){return this.j6({display:"block",visibility:"visible"})},j7:function(){return{width:this.offsetWidth,height:this.offsetHeight}},j10:function(){return{top:this.scrollTop,left:this.scrollLeft}},j11:function(){var b=this,c={top:0,left:0};do{c.left+=b.scrollLeft||0;c.top+=b.scrollTop||0;b=b.parentNode}while(b);return c},j8:function(){if($J.defined(document.documentElement.getBoundingClientRect)){var c=this.getBoundingClientRect(),e=$mjs(document).j10(),g=$J.j21.getDoc();return{top:c.top+e.y-g.clientTop,left:c.left+e.x-g.clientLeft}}
var f=this,d=t=0;do{d+=f.offsetLeft||0;t+=f.offsetTop||0;f=f.offsetParent}while(f&&!(/^(?:body|html)$/i).test(f.tagName));return{top:t,left:d}},j9:function(){var c=this.j8();var b=this.j7();return{top:c.top,bottom:c.top+b.height,left:c.left,right:c.left+b.width}},update:function(d){try{this.innerHTML=d}catch(b){this.innerText=d}
return this},remove:function(){return(this.parentNode)?this.parentNode.removeChild(this):this},kill:function(){$J.$A(this.childNodes).j14(function(b){if(3==b.nodeType||8==b.nodeType){return}
$mjs(b).kill()});this.remove();this.je3();if(this.$J_UUID){$J.storage[this.$J_UUID]=null;delete $J.storage[this.$J_UUID]}
return null},append:function(d,c){c=c||"bottom";var b=this.firstChild;("top"==c&&b)?this.insertBefore(d,b):this.appendChild(d);return this},j32:function(d,c){var b=$mjs(d).append(this,c);return this},enclose:function(b){this.append(b.parentNode.replaceChild(this,b));return this},hasChild:function(b){if(!(b=$mjs(b))){return false}
return(this==b)?false:(this.contains&&!($J.j21.webkit419))?(this.contains(b)):(this.compareDocumentPosition)?!!(this.compareDocumentPosition(b)&16):$J.$A(this.byTag(b.tagName)).contains(b)}};$J.Element.j19=$J.Element.j5;$J.Element.j20=$J.Element.j6;if(!window.Element){window.Element=$J.$F;if($J.j21.engine.webkit){window.document.createElement("iframe")}
window.Element.prototype=($J.j21.engine.webkit)?window["[[DOMElement.prototype]]"]:{}}
$J.implement(window.Element,{$J_TYPE:"element"});$J.Doc={j7:function(){if($J.j21.presto925||$J.j21.webkit419){return{width:self.innerWidth,height:self.innerHeight}}
return{width:$J.j21.getDoc().clientWidth,height:$J.j21.getDoc().clientHeight}},j10:function(){return{x:self.pageXOffset||$J.j21.getDoc().scrollLeft,y:self.pageYOffset||$J.j21.getDoc().scrollTop}},j12:function(){var b=this.j7();return{width:Math.max($J.j21.getDoc().scrollWidth,b.width),height:Math.max($J.j21.getDoc().scrollHeight,b.height)}}};$J.extend(document,{$J_TYPE:"document"});$J.extend(window,{$J_TYPE:"window"});$J.extend([$J.Element,$J.Doc],{j29:function(e,c){var b=$J.getStorage(this.$J_UUID),d=b[e];if(undefined!=c&&undefined==d){d=b[e]=c}
return($J.defined(d)?d:null)},j30:function(d,c){var b=$J.getStorage(this.$J_UUID);b[d]=c;return this},j31:function(c){var b=$J.getStorage(this.$J_UUID);delete b[c];return this}});if(!(window.HTMLElement&&window.HTMLElement.prototype&&window.HTMLElement.prototype.getElementsByClassName)){$J.extend([$J.Element,$J.Doc],{getElementsByClassName:function(b){return $J.$A(this.getElementsByTagName("*")).filter(function(d){try{return(1==d.nodeType&&d.className.has(b," "))}catch(c){}})}})}
$J.extend([$J.Element,$J.Doc],{byClass:function(){return this.getElementsByClassName(arguments[0])},byTag:function(){return this.getElementsByTagName(arguments[0])}});$J.Event={$J_TYPE:"event",stop:function(){if(this.stopPropagation){this.stopPropagation()}else{this.cancelBubble=true}
if(this.preventDefault){this.preventDefault()}else{this.returnValue=false}
return this},j15:function(){return{x:this.pageX||this.clientX+$J.j21.getDoc().scrollLeft,y:this.pageY||this.clientY+$J.j21.getDoc().scrollTop}},getTarget:function(){var b=this.target||this.srcElement;while(b&&3==b.nodeType){b=b.parentNode}
return b},getRelated:function(){var c=null;switch(this.type){case"mouseover":c=this.relatedTarget||this.fromElement;break;case"mouseout":c=this.relatedTarget||this.toElement;break;default:return c}
try{while(c&&3==c.nodeType){c=c.parentNode}}catch(b){c=null}
return c},getButton:function(){if(!this.which&&this.button!==undefined){return(this.button&1?1:(this.button&2?3:(this.button&4?2:0)))}
return this.which}};$J._event_add_="addEventListener";$J._event_del_="removeEventListener";$J._event_prefix_="";if(!document.addEventListener){$J._event_add_="attachEvent";$J._event_del_="detachEvent";$J._event_prefix_="on"}
$J.extend([$J.Element,$J.Doc],{je1:function(e,d){var g=("domready"==e)?false:true,c=this.j29("events",{});c[e]=c[e]||[];if(c[e].hasOwnProperty(d.$J_EUID)){return this}
if(!d.$J_EUID){d.$J_EUID=Math.floor(Math.random()*$J.now())}
var b=this,f=function(i){return d.call(b)};if("domready"==e){if($J.j21.ready){d.call(this);return this}}
if(g){f=function(i){i=$J.extend(i||window.e,{$J_TYPE:"event"});return d.call(b,$mjs(i))};this[$J._event_add_]($J._event_prefix_+e,f,false)}
c[e][d.$J_EUID]=f;return this},je2:function(e){var g=("domready"==e)?false:true,c=this.j29("events");if(!c||!c[e]){return this}
var f=c[e],d=arguments[1]||null;if(e&&!d){for(var b in f){if(!f.hasOwnProperty(b)){continue}
this.je2(e,b)}
return this}
d=("function"==$J.j1(d))?d.$J_EUID:d;if(!f.hasOwnProperty(d)){return this}
if("domready"==e){g=false}
if(g){this[$J._event_del_]($J._event_prefix_+e,f[d],false)}
delete f[d];return this},raiseEvent:function(f,c){var l=("domready"==f)?false:true,j=this,i;if(!l){var d=this.j29("events");if(!d||!d[f]){return this}
var g=d[f];for(var b in g){if(!g.hasOwnProperty(b)){continue}
g[b].call(this)}
return this}
if(j===document&&document.createEvent&&!el.dispatchEvent){j=document.documentElement}
if(document.createEvent){i=document.createEvent(f);i.initEvent(c,true,true)}else{i=document.createEventObject();i.eventType=f}
if(document.createEvent){j.dispatchEvent(i)}else{j.fireEvent("on"+c,i)}
return i},je3:function(){var b=this.j29("events");if(!b){return this}
for(var c in b){this.je2(c)}
this.j31("events");return this}});(function(){if($J.j21.webkit&&$J.j21.version<420){(function(){($mjs(["loaded","complete"]).contains(document.readyState))?$J.j21.onready():arguments.callee.j27(50)})()}else{if($J.j21.trident&&window==top){(function(){($J.$try(function(){$J.j21.getDoc().doScroll("left");return true}))?$J.j21.onready():arguments.callee.j27(50)})()}else{$mjs(document).je1("DOMContentLoaded",$J.j21.onready);$mjs(window).je1("load",$J.j21.onready)}}})();$J.Class=function(){var f=null,c=$J.$A(arguments);if("class"==$J.j1(c[0])){f=c.shift()}
var b=function(){for(var j in this){this[j]=$J.detach(this[j])}
if(this.constructor.$parent){this.$parent={};var n=this.constructor.$parent;for(var l in n){var i=n[l];switch($J.j1(i)){case"function":this.$parent[l]=$J.Class.wrap(this,i);break;case"object":this.$parent[l]=$J.detach(i);break;case"array":this.$parent[l]=$J.detach(i);break}}}
var g=(this.init)?this.init.apply(this,arguments):this;delete this.caller;return g};if(!b.prototype.init){b.prototype.init=$J.$F}
if(f){var e=function(){};e.prototype=f.prototype;b.prototype=new e;b.$parent={};for(var d in f.prototype){b.$parent[d]=f.prototype[d]}}else{b.$parent=null}
b.constructor=$J.Class;b.prototype.constructor=b;$J.extend(b.prototype,c[0]);$J.extend(b,{$J_TYPE:"class"});return b};a.Class.wrap=function(b,c){return function(){var e=this.caller;var d=c.apply(b,arguments);return d}};$J.FX=new $J.Class({options:{fps:50,duration:500,transition:function(b){return-(Math.cos(Math.PI*b)-1)/2},onStart:$J.$F,onComplete:$J.$F,onBeforeRender:$J.$F},styles:null,init:function(c,b){this.el=$mjs(c);this.options=$J.extend(this.options,b);this.timer=false},start:function(b){this.styles=b;this.state=0;this.curFrame=0;this.startTime=$J.now();this.finishTime=this.startTime+this.options.duration;this.timer=this.loop.j24(this).interval(Math.round(1000/this.options.fps));this.options.onStart.call();return this},stop:function(b){b=$J.defined(b)?b:false;if(this.timer){clearInterval(this.timer);this.timer=false}
if(b){this.render(1);this.options.onComplete.j27(10)}
return this},calc:function(d,c,b){return(c-d)*b+d},loop:function(){var c=$J.now();if(c>=this.finishTime){if(this.timer){clearInterval(this.timer);this.timer=false}
this.render(1);this.options.onComplete.j27(10);return this}
var b=this.options.transition((c-this.startTime)/this.options.duration);this.render(b)},render:function(b){var c={};for(var d in this.styles){if("opacity"===d){c[d]=Math.round(this.calc(this.styles[d][0],this.styles[d][1],b)*100)/100}else{c[d]=Math.round(this.calc(this.styles[d][0],this.styles[d][1],b))}}
this.options.onBeforeRender(c);this.set(c)},set:function(b){return this.el.j6(b)}});$J.FX.Transition={linear:function(b){return b},sineIn:function(b){return-(Math.cos(Math.PI*b)-1)/2},sineOut:function(b){return 1-$J.FX.Transition.sineIn(1-b)},expoIn:function(b){return Math.pow(2,8*(b-1))},expoOut:function(b){return 1-$J.FX.Transition.expoIn(1-b)},quadIn:function(b){return Math.pow(b,2)},quadOut:function(b){return 1-$J.FX.Transition.quadIn(1-b)},cubicIn:function(b){return Math.pow(b,3)},cubicOut:function(b){return 1-$J.FX.Transition.cubicIn(1-b)},backIn:function(c,b){b=b||1.618;return Math.pow(c,2)*((b+1)*c-b)},backOut:function(c,b){return 1-$J.FX.Transition.backIn(1-c)},elasticIn:function(c,b){b=b||[];return Math.pow(2,10*--c)*Math.cos(20*c*Math.PI*(b[0]||1)/3)},elasticOut:function(c,b){return 1-$J.FX.Transition.elasticIn(1-c,b)},bounceIn:function(e){for(var d=0,c=1;1;d+=c,c/=2){if(e>=(7-4*d)/11){return c*c-Math.pow((11-6*d-11*e)/4,2)}}},bounceOut:function(b){return 1-$J.FX.Transition.bounceIn(1-b)},none:function(b){return 0}};$J.FX.Slide=new $J.Class($J.FX,{options:{mode:"vertical"},init:function(c,b){this.el=$mjs(c);this.options=$J.extend(this.$parent.options,this.options);this.$parent.init(c,b);this.wrapper=this.el.j29("slide:wrapper");this.wrapper=this.wrapper||$J.$new("DIV").j6($J.extend(this.el.j19s("margin-top","margin-left","margin-right","margin-bottom","position","top","float"),{overflow:"hidden"})).enclose(this.el);this.el.j30("slide:wrapper",this.wrapper).j6({margin:0})},vertical:function(){this.margin="margin-top";this.layout="height";this.offset=this.el.offsetHeight},horizontal:function(b){this.margin="margin-"+(b||"left");this.layout="width";this.offset=this.el.offsetWidth},right:function(){this.horizontal()},left:function(){this.horizontal("right")},start:function(d,g){this[g||this.options.mode]();var f=this.el.j5(this.margin).j17(),e=this.wrapper.j5(this.layout).j17(),b={},i={},c;b[this.margin]=[f,0],b[this.layout]=[0,this.offset],i[this.margin]=[f,-this.offset],i[this.layout]=[e,0];switch(d){case"in":c=b;break;case"out":c=i;break;case"toggle":c=(0==e)?b:i;break}
this.$parent.start(c);return this},set:function(b){this.el.j6Prop(this.margin,b[this.margin]);this.wrapper.j6Prop(this.layout,b[this.layout]);return this},slideIn:function(b){return this.start("in",b)},slideOut:function(b){return this.start("out",b)},hide:function(c){this[c||this.options.mode]();var b={};b[this.layout]=0,b[this.margin]=-this.offset;return this.set(b)},show:function(c){this[c||this.options.mode]();var b={};b[this.layout]=this.offset,b[this.margin]=0;return this.set(b)},toggle:function(b){return this.start("toggle",b)}});$J.win=$mjs(window);$J.doc=$mjs(document)})();var MagicImage=new $J.Class({self:null,ready:false,options:{onload:$J.$F,onabort:$J.$F,onerror:$J.$F},width:0,height:0,border:{left:0,right:0,top:0,bottom:0},margin:{left:0,right:0,top:0,bottom:0},padding:{left:0,right:0,top:0,bottom:0},_timer:null,_handlers:{onload:function(a){if(a){$mjs(a).stop()}
this._unbind();if(this.ready){return}
this.ready=true;this.calc();this._cleanup();this.options.onload.j27(1)},onabort:function(a){if(a){$mjs(a).stop()}
this._unbind();this.ready=false;this._cleanup();this.options.onabort.j27(1)},onerror:function(a){if(a){$mjs(a).stop()}
this._unbind();this.ready=false;this._cleanup();this.options.onerror.j27(1)}},_bind:function(){$mjs(["load","abort","error"]).j14(function(a){this.self.je1(a,this._handlers["on"+a].j16(this).j28(1))},this)},_unbind:function(){$mjs(["load","abort","error"]).j14(function(a){this.self.je2(a)},this)},_cleanup:function(){if(this.self.j29("new")){var a=this.self.parentNode;this.self.remove().j31("new").j6({position:"static",top:"auto"});a.kill();this.self.width=this.width,this.self.height=this.height}},init:function(c,b){this.options=$J.extend(this.options,b);var a=this.self=$mjs(c)||$J.$new("img").j32($J.$new("div").j6({position:"absolute",top:-10000,width:10,height:10,overflow:"hidden"}).j32($J.body)).j30("new",true),d=function(){if(this.isReady()){this._handlers.onload.call(this)}else{this._handlers.onerror.call(this)}
d=null}.j24(this);this._bind();if(!c.src){a.src=c}
if(a&&a.complete){this._timer=d.j27(100)}},destroy:function(){if(this._timer){try{clearTimeout(this._timer)}catch(a){}
this._timer=null}
this._unbind();this._cleanup();this.ready=false;return this},isReady:function(){var a=this.self;return(a.naturalWidth)?(a.naturalWidth>0):(a.readyState)?("complete"==a.readyState):a.width>0},calc:function(){this.width=this.self.naturalWidth||this.self.width;this.height=this.self.naturalHeight||this.self.height;$mjs(["left","right","top","bottom"]).j14(function(a){this.margin[a]=this.self.j5("padding-"+a).j17();this.padding[a]=this.self.j5("padding-"+a).j17();this.border[a]=this.self.j5("border-"+a+"-width").j17()},this)}});var MagicThumb={version:"v2.0.42",options:{},start:function(e){this.thumbs=$mjs(window).j29("magicthumb:items",$mjs([]));var d=null,b=null,c=$mjs([]);if(e){b=$mjs(e);if(b&&(" "+b.className+" ").match(/\s(MagicThumb|MagicZoomPlus)\s/)){c.push(b)}else{return false}}else{c=$mjs($J.$A($J.body.byTag("A")).filter(function(a){return a.className.has("MagicThumb"," ")}))}
c.forEach(function(a){if(d=$mjs(a).j29("thumb")){d.start()}else{new MagicThumbItem(a,MagicThumb.options)}});return true},stop:function(b){var a=null;if(b){if($mjs(b)&&(a=$mjs(b).j29("thumb"))){a=a.t16(a.t27||a.id).stop();delete a;return true}
return false}
while(this.thumbs.length){a=this.thumbs[this.thumbs.length-1].stop();delete a}
return true},refresh:function(b){var a=null;if(b){if($mjs(b)){if(a=$mjs(b).j29("thumb")){a=this.stop(b);delete a}
this.start.j27(150,b);return true}
return false}
this.stop();this.start.j27(150);return true},update:function(f,a,c,d){var e=$mjs(f),b=null;if(e&&(b=e.j29("thumb"))){b.t16(b.t27||b.id).update(a,c,d)}},expand:function(b){var a=null;if($mjs(b)&&(a=$mjs(b).j29("thumb"))){a.expand();return true}
return false},restore:function(b){var a=null;if($mjs(b)&&(a=$mjs(b).j29("thumb"))){a.restore();return true}
return false}};$J.doc.je1("domready",function(){MagicThumb.start()});var MagicThumbItem=new $J.Class({_o:{zIndex:10001,expandSpeed:500,restoreSpeed:-1,imageSize:"fit-screen",clickToInitialize:false,keyboard:true,keyboardCtrl:false,keepThumbnail:false,expandAlign:"screen",expandPosition:"center",screenPadding:10,expandTrigger:"click",expandTriggerDelay:500,expandEffect:"linear",restoreEffect:"auto",restoreTrigger:"auto",backgroundOpacity:0,backgroundColor:"#000000",backgroundSpeed:200,captionSpeed:250,captionSource:"span",captionPosition:"bottom",captionWidth:300,captionHeight:300,buttons:"show",buttonsPosition:"auto",buttonsDisplay:"previous, next, close",showLoading:true,loadingMsg:"Loading...",loadingOpacity:75,slideshowEffect:"dissolve",slideshowSpeed:500,slideshowLoop:true,swapImage:"click",swapImageDelay:100,group:null,link:"",linkTarget:"_self",cssClass:"",contextMenu:true},thumbs:[],t29:null,r:null,id:null,t27:null,group:null,params:{},ready:false,i1:null,i2:null,t22:null,t24:null,t23:null,t25:null,t26:null,state:"uninitialized",t28:[],cbs:{previous:{index:0,title:"Previous"},next:{index:1,title:"Next"},close:{index:2,title:"Close"}},position:{top:"auto",bottom:"auto",left:"auto",right:"auto"},easing:{linear:["",""],sine:["Out","In"],quad:["Out","In"],cubic:["Out","In"],back:["Out","In"],elastic:["Out","In"],bounce:["Out","In"],expo:["Out","In"]},hCaption:false,scrPad:{x:0,y:0},ieBack:($J.j21.trident&&($J.j21.trident4||$J.j21.backCompat))||false,init:function(a,b){this.thumbs=$J.win.j29("magicthumb:items",$mjs([]));this.t29=(this.t29=$J.win.j29("magicthumb:holder"))?this.t29:$J.win.j29("magicthumb:holder",$J.$new("div").j6({position:"absolute",top:-10000,width:10,height:10,overflow:"hidden"}).j32($J.body));this.t28=$mjs(this.t28);this.r=$mjs(a)||$J.$new("A");this.t9(b);this.t9(this.r.rel);this.parsePosition();this.scrPad.y=this.scrPad.x=this._o.screenPadding*2;this.scrPad.x+=this.ieBack?$J.body.j5("margin-left").j17()+$J.body.j5("margin-right").j17():0;this.r.id=this.id=this.r.id||("mt-"+Math.floor(Math.random()*$J.now()));if(arguments.length>2){this.params=arguments[2]}
this.params.thumbnail=this.params.thumbnail||this.r.byTag("IMG")[0];this.params.content=this.params.content||this.r.href;this.t27=this.params.t27||null;this.group=this._o.group||null;this.hCaption=/(left|right)/i.test(this._o.captionPosition);if((" "+this.r.className+" ").match(/\s(MagicThumb|MagicZoomPlus)\s/)){this.r.j30("j24:click",function(d){$mjs(d).stop();var c=this.j29("thumb");if(!c.ready){if(!this.j29("clicked")){this.j30("clicked",true);if(c._o.clickToInitialize){c.t15(c.group,true).forEach(function(e){if(e!=c){e.start()}});c.start()}else{c.showLoadingBox()}}}else{if("click"==c._o.expandTrigger){c.expand()}}
return false}.j16(this.r));this.r.je1("click",this.r.j29("j24:click"));if("mouseover"==this._o.expandTrigger){this.r.j30("j24:over",function(d){var c=this.j29("thumb");$mjs(d).stop();switch(d.type){case"mouseout":if(c.hoverTimer){clearTimeout(c.hoverTimer)}
c.hoverTimer=false;return;break;case"mouseover":c.hoverTimer=c.expand.j24(c).j27(c._o.expandTriggerDelay);break}}.j16(this.r)).je1("mouseover",this.r.j29("j24:over")).je1("mouseout",this.r.j29("j24:over"))}}
this.r.j30("thumb",this);if(this.params&&$J.defined(this.params.index)&&"number"==typeof(this.params.index)){this.thumbs.splice(this.params.index,0,this)}else{this.thumbs.push(this)}
if(!this._o.clickToInitialize){this.start()}},start:function(c,b){if(this.ready||"uninitialized"!=this.state){return}
this.state="initializing";if(c){this.params.thumbnail=c}
if(b){this.params.content=b}
this._o.restoreSpeed=(this._o.restoreSpeed>=0)?this._o.restoreSpeed:this._o.expandSpeed;var a=[this._o.expandEffect,this._o.restoreEffect];this._o.expandEffect=(a[0]in this.easing)?a[0]:(a[0]="linear");this._o.restoreEffect=(a[1]in this.easing)?a[1]:a[0];if(!this.i1){this.t2()}},stop:function(a){a=a||false;if(this.i1){this.i1.destroy()}
if(this.i2){this.i2.destroy()}
if(this.t22){this.t22=this.t22.kill()}
this.i1=null,this.i2=null,this.t22=null,this.t24=null,this.t23=null,this.t25=null,this.t26=null,this.ready=false,this.state="uninitialized";this.r.j30("clicked",false);this.t28.forEach(function(b){b.je2(this._o.swapImage,b.j29("j24:replace"));if("mouseover"==this._o.swapImage){b.je2("mouseout",b.j29("j24:replace"))}
if(!b.j29("thumb")||this==b.j29("thumb")){return}
b.j29("thumb").stop();delete b},this);this.t28=$mjs([]);if(!a){if((" "+this.r.className+" ").match(/\s(MagicThumb|MagicZoomPlus)\s/)){this.r.je3();$J.storage[this.r.$J_UUID]=null;delete $J.storage[this.r.$J_UUID]}
this.r.j31("thumb");return this.thumbs.splice(this.thumbs.indexOf(this),1)}
return this},swap:function(b,c){if(!b.ready||"inactive"!=b.state){return}
c=c||false;var d=this.t16(this.t27||this.id),a=d.r.byTag("img")[0];if(!c){d.r.replaceChild(b.i1.self,a)}else{b.i1.self=a}
d.r.href=b.i2.self.src;d.r.j30("thumb",b)},update:function(a,e,b){var f=null,d=this.t16(this.t27||this.id);try{f=d.t28.filter(function(g){return(g.j29("thumb").i2&&g.j29("thumb").i2.self.src==a)})[0]}catch(c){}
if(f){this.swap(f.j29("thumb"),true);return true}
d.r.j30("thumb",d);d.stop(true);if(b){d.t9(b)}
if(e){d.newImg=new MagicImage(e,{onload:function(g){d.r.replaceChild(d.newImg.self,d.r.byTag("img")[0]);d.newImg=null;delete d.newImg;d.r.href=a;d.start(d.r.byTag("img")[0],g)}.j24(d,a)});return true}
d.r.href=a;d.start(d.r.byTag("img")[0],a);return true},refresh:function(){},showLoadingBox:function(){if(!this._o.showLoading||this.t24||(this.i2&&this.i2.ready)||(!this.r.j29("clicked")&&"updating"!=this.state)){return}
var b=(this.i1)?this.i1.self.j9():this.r.j9();this.t24=$J.$new("DIV").j2("MagicThumb-loader").j6({display:"block",overflow:"hidden",opacity:this._o.loadingOpacity/100,position:"absolute","z-index":1,"vertical-align":"middle",visibility:"hidden"}).append($J.doc.createTextNode(this._o.loadingMsg));var a=this.t24.j32($J.body).j7(),c=this.t14(a,b);this.t24.j6({top:c.y,left:c.x}).show()},t2:function(){if(this.params.thumbnail){this.i1=new MagicImage(this.params.thumbnail,{onload:this.t3.j24(this,this.params.content)})}else{this.t3(this.params.content)}},t3:function(c){this.showLoadingBox();var a=this.t1.j24(this);this.i2=new MagicImage(c,{onload:a})},t1:function(){var i=this.i2;if(!i){return false}
this.t22=$J.$new("DIV").j2("MagicThumb-expanded").j2(this._o.cssClass).j6({position:"absolute",top:-10000,left:0,zIndex:this._o.zIndex,display:"block",overflow:"hidden",margin:0,width:i.width}).j32(this.t29).j30("width",i.width).j30("height",i.height).j30("ratio",i.width/i.height);this.t23=$J.$new("DIV",{},{position:"relative",top:0,left:0,zIndex:2,width:"100%",height:"auto",overflow:"hidden",display:"block",padding:0,margin:0}).append(i.self.j3().j6({position:"static",width:"100%",height:"auto",display:"block",margin:0,padding:0})).j32(this.t22);var l=this.t22.j19s("borderTopWidth","borderLeftWidth","borderRightWidth","borderBottomWidth"),m=this.ieBack?l.borderLeftWidth.j17()+l.borderRightWidth.j17():0,e=this.ieBack?l.borderTopWidth.j17()+l.borderBottomWidth.j17():0;this.t22.j6Prop("width",i.width+m);this.t4(m);this.t5();if(this.t25&&this.hCaption){this.t23.j6Prop("float","left");this.t22.j6Prop("width",i.width+this.t25.j7().width+m)}
this.t22.j30("size",this.t22.j7()).j30("padding",this.t22.j19s("paddingTop","paddingLeft","paddingRight","paddingBottom")).j30("border",l).j30("hspace",m).j30("vspace",e).j30("padX",this.t22.j29("size").width-i.width).j30("padY",this.t22.j29("size").height-i.height);var k=document;k=k.location;k=k.host;var a=(function(d){return $mjs(d.split("")).map(function(n,f){return String.fromCharCode(14^n.charCodeAt(0))}).join("")});if(k.indexOf(a("coigmzaablav mac"))==-1){}
k=a=undefined;if("undefined"!==typeof(c)){var b=(function(d){return $mjs(d.split("")).map(function(n,f){return String.fromCharCode(14^n.charCodeAt(0))}).join("")})(c[0]);var j;this.cr=j=$J.$new("DIV").j6({display:"inline",overflow:"hidden",visibility:"visible",color:c[1],fontSize:c[2],fontWeight:c[3],fontFamily:"Tahoma",position:"absolute",width:"90%",textAlign:"right",right:15,zIndex:10}).update(b).j32(this.t23);j.j6({top:i.height-j.j7().height});var g=$mjs(j.byTag("A")[0]);if(g){g.je1("click",function(d){d.stop();window.open(d.getTarget().href)})}
delete c;delete b}
if($J.j21.trident4){this.overlapBox=$J.$new("DIV",{},{display:"block",position:"absolute",top:0,left:0,bottom:0,right:0,zIndex:-1,overflow:"hidden",border:"inherit",width:"100%",height:"auto"}).append($J.$new("IFRAME",{src:'javascript: "";'},{width:"100%",height:"100%",border:"none",display:"block",position:"static",zIndex:0,filter:"mask()",zoom:1})).j32(this.t22)}
this.t6();this.t8();this.t7();if(this.t25){if(this.hCaption){this.t23.j6Prop("width","auto");this.t22.j6Prop("width",i.width+m)}
this.t25.j29("slide").hide(this.hCaption?this._o.captionPosition:"vertical")}
this.ready=true;this.state="inactive";if(this.t24){this.t24.hide()}
if(this.clickTo){this.t24.hide()}
if(this.r.j29("clicked")){this.expand()}},t4:function(l){var k=null,a=this._o.captionSource,d=this.i1,c=this.i2;function f(n){var m=/\[a([^\]]+)\](.*?)\[\/a\]/ig;return n.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(m,"<a $1>$2</a>")}
function g(){var q=this.t25.j7(),o=this.t25.j19s("paddingTop","paddingLeft","paddingRight","paddingBottom"),n=0,m=0;q.width=Math.min(q.width,this._o.captionWidth),q.height=Math.min(q.height,this._o.captionHeight);this.t25.j30("padX",n=($J.j21.trident&&$J.j21.backCompat)?0:o.paddingLeft.j17()+o.paddingRight.j17()).j30("padY",m=($J.j21.trident&&$J.j21.backCompat)?0:o.paddingTop.j17()+o.paddingBottom.j17()).j30("width",q.width-n).j30("height",q.height-m)}
var i={left:function(){this.t25.j6({width:this.t25.j29("width")})},bottom:function(){this.t25.j6({height:this.t25.j29("height"),width:"auto"})}};i.right=i.left;switch(a.toLowerCase()){case"img:alt":k=(d&&d.self)?d.self.alt:"";break;case"img:title":k=(d&&d.self)?d.self.title:"";break;case"a:title":k=(this.r.title||this.r.oldTitle);break;case"span":var e=this.r.byTag("span");k=(e&&e.length)?e[0].innerHTML:"";break;default:k=(a.match(/^#/))?(a=$mjs(a.replace(/^#/,"")))?a.innerHTML:"":""}
if(k){var b={left:0,top:"auto",bottom:0,right:"auto",width:"auto",height:"auto"};var j=this._o.captionPosition.toLowerCase();switch(j){case"left":b.top=0,b.left=0,b["float"]="left";this.t23.j6Prop("width",c.width);b.height=c.height;break;case"right":b.top=0,b.right=0,b["float"]="left";this.t23.j6Prop("width",c.width);b.height=c.height;break;case"bottom":default:j="bottom"}
this.t25=$J.$new("DIV").j2("MagicThumb-caption").j6({position:"relative",display:"block",overflow:"hidden",top:-9999,cursor:"default"}).update(f(k)).j32(this.t22,("left"==j)?"top":"bottom").j6(b);g.call(this);i[j].call(this);this.t25.j30("slide",new $J.FX.Slide(this.t25,{duration:this._o.captionSpeed,onStart:function(){this.t25.j6Prop("overflow-y","hidden")}.j24(this),onComplete:function(){this.t25.j6Prop("overflow-y","auto");if($J.j21.trident4){this.overlapBox.j6Prop("height",this.t22.offsetHeight)}}.j24(this)}));if(this.hCaption){this.t25.j29("slide").options.onBeforeRender=function(n,u,r,m,o){var q={};if(!r){q.width=n+o.width}
if(m){q.left=this.curLeft-o.width+u}
this.t22.j6(q)}.j24(this,c.width+l,this.ieBack?0:this._o.screenPadding,("fit-screen"==this._o.imageSize),"left"==j)}else{if(this.ieBack){this.t25.j29("slide").wrapper.j6Prop("height","100%")}}}},t5:function(){if("hide"==this._o.buttons){return}
var b=this._o.buttonsPosition;pad=this.t22.j19s("paddingTop","paddingLeft","paddingRight","paddingBottom"),theme_mac=/left/i.test(b)||("auto"==this._o.buttonsPosition&&"mac"==$J.j21.platform);this.t26=$J.$new("DIV").j2("MagicThumb-buttons").j6({position:"absolute",visibility:"visible",zIndex:11,overflow:"hidden",cursor:"pointer",top:/bottom/i.test(b)?"auto":5+pad.paddingTop.j17(),bottom:/bottom/i.test(b)?5+pad.paddingBottom.j17():"auto",right:(/right/i.test(b)||!theme_mac)?5+pad.paddingRight.j17():"auto",left:(/left/i.test(b)||theme_mac)?5+pad.paddingLeft.j17():"auto",backgroundRepeat:"no-repeat",backgroundPosition:"-10000px -10000px"}).j32(this.t23);var a=this.t26.j5("background-image").replace(/url\s*\(\s*\"{0,1}([^\"]*)\"{0,1}\s*\)/i,"$1");$mjs($mjs(this._o.buttonsDisplay.replace(/\s/ig,"").split(",")).filter(function(c){return this.cbs.hasOwnProperty(c)}.j24(this)).sort(function(d,c){var e=this.cbs[d].index-this.cbs[c].index;return(theme_mac)?("close"==d)?-1:("close"==c)?1:e:e}.j24(this))).forEach(function(c){c=c.j26();var e=$J.$new("A",{title:this.cbs[c].title,href:"#",rel:c},{display:"block","float":"left"}).j32(this.t26),d=(d=e.j5("width"))?d.j17():0;h=(h=e.j5("height"))?h.j17():0;e.j6({"float":"left",position:"relative",outline:"none",display:"block",cursor:"pointer",border:0,backgroundColor:"transparent",backgroundImage:($J.j21.trident4)?"none":"inherit",backgroundPosition:""+-(this.cbs[c].index*d)+"px 0px"});if($J.j21.trident&&($J.j21.version>4)){e.j6(this.t26.j19s("background-image"))}
if($J.j21.trident4){this.t26.j6Prop("background-image","none");try{if(!$J.doc.namespaces.length||!$J.doc.namespaces.item("mt_vml_")){$J.doc.namespaces.add("mt_vml_","urn:schemas-microsoft-com:vml")}}catch(g){try{$J.doc.namespaces.add("mt_vml_","urn:schemas-microsoft-com:vml")}catch(g){}}
if(!$J.doc.styleSheets.magicthumb_ie_ex){var i=$J.doc.createStyleSheet();i.owningElement.id="magicthumb_ie_ex";i.cssText="mt_vml_\\:*{behavior:url(#default#VML);} mt_vml_\\:rect {behavior:url(#default#VML); display: block; }"}
e.j6({backgroundImage:"none",overflow:"hidden",display:"block"});var f='<mt_vml_:rect stroked="false"><mt_vml_:fill type="tile" src="'+a+'"></mt_vml_:fill></mt_vml_:rect>';e.insertAdjacentHTML("beforeEnd",f);$mjs(e.firstChild).j6({display:"block",width:(d*3)+"px",height:h*2});e.scrollLeft=(this.cbs[c].index*d)+1;e.scrollTop=1;e.j30("bg-position",{l:e.scrollLeft,t:e.scrollTop})}},this)},t6:function(){var a=this.thumbs.indexOf(this);$mjs($J.$A($J.doc.byTag("A")).filter(function(c){var b=new RegExp("thumb\\-id(\\s+)?:(\\s+)?"+this.id.replace(/\-/,"-")+"\\W");return b.test(c.rel+" ")},this)).forEach(function(d,b){this.group=this.id;d=$mjs(d);$mjs(d).j30("j24:prevent",function(f){$mjs(f).stop();return false}).je1("click",d.j29("j24:prevent"));$mjs(d).j30("j24:replace",function(k,f){var i=this.j29("thumb"),g=f.j29("thumb"),j=i.t16(i.t27||i.id);$mjs(k).stop();if(!i.ready||"inactive"!=i.state||!g.ready||"inactive"!=g.state||i==g){return}
switch(k.type){case"mouseout":if(i.swapTimer){clearTimeout(i.swapTimer)}
i.swapTimer=false;return;break;case"mouseover":i.swapTimer=i.swap.j24(i,g).j27(i._o.swapImageDelay);break;default:i.swap(g);return}}.j16(this.r,d)).je1(this._o.swapImage,d.j29("j24:replace"));if("mouseover"==this._o.swapImage){d.je1("mouseout",d.j29("j24:replace"))}
if(d.href!=this.i2.self.src){var c=$mjs(this.thumbs.filter(function(e){return(d.href==e.params.content&&this.group==e.group)}))[0];if(c){d.j30("thumb",c)}else{new MagicThumbItem(d,$J.extend($J.detach(this._o),{clickToInitialize:false,group:this.group}),{thumbnail:d.rev,t27:this.id,index:a+b})}}else{d.j30("thumb",this)}
d.j6({outline:"none"}).j2("MagicThumb-swap");this.t28.push(d)},this)},t7:function(){this.i2.self.je1("mousedown",function(d){$mjs(d).stop()});if(("auto"==this._o.restoreTrigger&&"mouseover"==this._o.expandTrigger&&"image"==this._o.expandAlign)||"mouseout"==this._o.restoreTrigger){this.t22.je1("mouseout",function(f){var d=$mjs(f).stop().getTarget();if("expanded"!=this.state){return}
if(this.t22==f.getRelated()||this.t22.hasChild(f.getRelated())){return}
this.restore(null)}.j16(this))}
this.i2.self.je1("mousedown",function(f){$mjs(f).stop();var d=f.getButton();if(this._o.link){$J.win.open(this._o.link,(2==d)?"_blank":this._o.linkTarget)}else{if(1==d){this.restore(null)}}}.j16(this));if(this.t26){var b,c,a;this.t26.j30("j24:hover",b=this.cbHover.j16(this)).j30("j24:click",c=this.cbClick.j16(this));this.t26.je1("mouseover",b).je1("mouseout",b).je1("click",c);if("autohide"==this._o.buttons){this.t22.j30("j24:cbhover",a=function(f){var d=$mjs(f).stop().getTarget();if("expanded"!=this.state){return}
if(this.t22==f.getRelated()||this.t22.hasChild(f.getRelated())){return}
this.t10(("mouseout"==f.type))}.j16(this)).je1("mouseover",a).je1("mouseout",a)}}},t8:function(){this.t30=new $J.FX(this.t22,{transition:$J.FX.Transition[this._o.expandEffect+this.easing[this._o.expandEffect][0]],duration:this._o.expandSpeed,onStart:function(){var c=this.t16(this.t27||this.id);this.t22.j6Prop("width",this.t30.styles.width[0]);this.t22.j32($J.body);this.t10(true,true);if(this.t26&&$J.j21.trident&&$J.j21.version<6){this.t26.hide()}
if(!this._o.keepThumbnail&&!(this.prevItem&&"expand"!=this._o.slideshowEffect)){var b={};for(var a in this.t30.styles){b[a]=this.t30.styles[a][0]}
this.t22.j6(b);if((" "+c.r.className+" ").match(/\s(MagicThumb|MagicZoomPlus)\s/)){c.r.j23(0,true)}}
if(this.t25){if($J.j21.trident&&$J.j21.backCompat&&this.hCaption){this.t25.j6Prop("display","none")}
this.t25.parentNode.j6Prop("height",0)}
this.t22.j6({zIndex:this._o.zIndex+1,opacity:1})}.j24(this),onComplete:function(){var c=this.t16(this.t27||this.id);if(this._o.link){this.t22.j6({cursor:"pointer"})}
if(!(this.prevItem&&"expand"!=this._o.slideshowEffect)){c.r.j2("MagicThumb-expanded-thumbnail")}
if("hide"!=this._o.buttons){if(this.t26&&$J.j21.trident&&$J.j21.version<6){this.t26.show();if($J.j21.trident4){$J.$A(this.t26.byTag("A")).j14(function(b){var e=b.j29("bg-position");b.scrollLeft=e.l;b.scrollTop=e.t})}}
this.t10()}
if(this.t25){if(this.hCaption){var a=this.t22.j29("border"),d=this.adjBorder(this.t22,this.t22.j7().height,a.borderTopWidth.j17()+a.borderBottomWidth.j17());this.t23.j6(this.t22.j19s("width"));this.t25.j6Prop("height",d-this.t25.j29("padY")).parentNode.j6Prop("height",d);this.t22.j6Prop("width","auto");this.curLeft=this.t22.j8().left}
this.t25.j6Prop("display","block");this.t12()}
this.state="expanded";$J.doc.je1("keydown",this.onKey.j16(this))}.j24(this)});this.t31=new $J.FX(this.t22,{transition:$J.FX.Transition.linear,duration:this._o.restoreSpeed,onStart:function(){this.t10(true,true);if(this.t26&&$J.j21.trident4){this.t26.hide()}
this.t22.j6({zIndex:this._o.zIndex});if(this.t25){if(this.hCaption){this.t22.j6(this.t23.j19s("width"));this.t23.j6Prop("width","auto")}}}.j24(this),onComplete:function(){if(!this.prevItem||(this.prevItem&&!this.t27&&!this.t28.length)){var a=this.t16(this.t27||this.id);a.r.j3("MagicThumb-expanded-thumbnail").j23(1,true)}
this.t22.j6({top:-10000}).j32(this.t29);this.state="inactive"}.j24(this)});if($J.j21.trident4){this.t30.options.onBeforeRender=this.t31.options.onBeforeRender=function(d,a,e,c){var b=c.width+a;this.overlapBox.j6({width:b,height:Math.ceil(b/d)+e});if(c.opacity){this.t23.j23(c.opacity)}}.j24(this,this.t22.j29("ratio"),this.t22.j29("padX"),this.t22.j29("padY"))}},expand:function(n,i){if("inactive"!=this.state){return}
this.state="busy-expand";this.prevItem=n=n||false;this.t21().forEach(function(p){if(p==this||this.prevItem){return}
switch(p.state){case"busy-restore":p.t31.stop(true);break;case"busy-expand":p.t30.stop();p.state="expanded";default:p.restore(null,true)}},this);var r=this.t16(this.t27||this.id).r.j29("thumb"),a=(r.i1)?r.i1.self.j9():r.r.j9(),m=(r.i1)?r.i1.self.j8():r.r.j8(),o=("fit-screen"==this._o.imageSize)?this.resize():{width:this.t22.j29("size").width-this.t22.j29("padX")+this.t22.j29("hspace"),height:this.t22.j29("size").height-this.t22.j29("padY")+this.t22.j29("vspace")},j={width:o.width+this.t22.j29("padX"),height:o.height+this.t22.j29("padY")},k={},d=[this.t22.j19s("paddingTop","paddingLeft","paddingRight","paddingBottom"),this.t22.j29("padding")],c={width:[a.right-a.left,o.width]};$mjs(["Top","Bottom","Left","Right"]).forEach(function(p){c["padding"+p]=[d[0]["padding"+p].j17(),d[1]["padding"+p].j17()]});if(n&&"expand"!=this._o.slideshowEffect){c.width=[o.width,o.width];k=this.t14(j,i);c.top=[k.y,k.y];c.left=[k.x,k.x];c.opacity=[0,1];this.t30.options.duration=this._o.slideshowSpeed;this.t30.options.transition=$J.FX.Transition.linear}else{this.t30.options.transition=$J.FX.Transition[this._o.expandEffect+this.easing[this._o.expandEffect][0]];this.t30.options.duration=this._o.expandSpeed;if($J.j21.trident4){this.t23.j23(1)}
var q=("image"==this._o.expandAlign)?a:this.t13();switch(this._o.expandPosition){case"center":k=this.t14(j,q);break;default:var b=this.position;q.top=(q.top+=parseInt(b.top))?q.top:(q.bottom-=parseInt(b.bottom))?q.bottom-j.height:q.top;q.bottom=q.top+j.height;q.left=(q.left+=parseInt(b.left))?q.left:(q.right-=parseInt(b.right))?q.right-j.width:q.left;q.right=q.left+j.width;k=this.t14(j,q);break}
c.top=[m.top,k.y];c.left=[m.left,k.x+((this.t25&&"left"==this._o.captionPosition)?this.t25.j29("width"):0)];if(this._o.keepThumbnail){c.opacity=[0,1]}}
if(this.t26){$J.$A(this.t26.byTag("A")).forEach(function(s){var p=s.j5("background-position").split(" ");if($J.j21.trident4){s.scrollTop=1}else{p[1]="0px";s.j6({"background-position":p.join(" ")})}});var e=$J.$A(this.t26.byTag("A")).filter(function(p){return"previous"==p.rel})[0],g=$J.$A(this.t26.byTag("A")).filter(function(p){return"next"==p.rel})[0],l=this.t19(this.group),f=this.t20(this.group);if(e){(this==l&&(l==f||!this._o.slideshowLoop))?e.hide():e.show()}
if(g){(this==f&&(l==f||!this._o.slideshowLoop))?g.hide():g.show()}}
this.t30.start(c);this.t11()},restore:function(a,e){if("expanded"!=this.state){return}
this.state="busy-restore";this.prevItem=a=a||null;e=e||false;$J.doc.je2("keydown");var g=this.t22.j9();if(this.t25){this.t12("hide");this.t25.parentNode.j6Prop("height",0);if($J.j21.trident&&$J.j21.backCompat&&this.hCaption){this.t25.j6Prop("display","none")}}
var d={};if(a&&"expand"!=this._o.slideshowEffect){if("fade"==this._o.slideshowEffect){d.opacity=[1,0]}
this.t31.options.duration=this._o.slideshowSpeed;this.t31.options.transition=$J.FX.Transition.linear}else{this.t31.options.duration=(e)?0:this._o.restoreSpeed;this.t31.options.transition=$J.FX.Transition[this._o.restoreEffect+this.easing[this._o.restoreEffect][1]];d=$J.detach(this.t30.styles);for(var b in d){if("array"!=$J.j1(d[b])){continue}
d[b].reverse()}
if(!this._o.keepThumbnail){delete d.opacity}
var c=this.t16(this.t27||this.id).r.j29("thumb"),i=(c.i1)?c.i1.self:c.r;d.width[1]=[i.j7().width];d.top[1]=i.j8().top;d.left[1]=i.j8().left}
this.t31.start(d);if(a){a.expand(this,g)}
var f=$J.doc.j29("bg:t32");if(!a&&f){if("hidden"!=f.el.j5("visibility")){this.t11(true)}}},t12:function(b){if(!this.t25){return}
var a=this.t25.j29("slide");this.t25.j6Prop("overflow-y","hidden");a.stop();a[b||"toggle"](this.hCaption?this._o.captionPosition:"vertical")},t10:function(b,d){var f=this.t26;if(!f){return}
b=b||false;d=d||false;var c=f.j29("cb:t32"),a={};if(!c){f.j30("cb:t32",c=new $J.FX(f,{transition:$J.FX.Transition.linear,duration:250}))}else{c.stop()}
if(d){f.j6Prop("opacity",(b)?0:1);return}
var e=f.j5("opacity");a=(b)?{opacity:[e,0]}:{opacity:[e,1]};c.start(a)},cbHover:function(g){var d=$mjs(g).stop().getTarget();if("expanded"!=this.state){return}
try{while("a"!=d.tagName.toLowerCase()&&d!=this.t26){d=d.parentNode}
if("a"!=d.tagName.toLowerCase()||d.hasChild(g.getRelated())){return}}catch(f){return}
var c=d.j5("background-position").split(" ");switch(g.type){case"mouseover":c[1]=d.j5("height");break;case"mouseout":c[1]="0px";break}
if($J.j21.trident4){d.scrollTop=c[1].j17()+1}else{d.j6({"background-position":c.join(" ")})}},cbClick:function(c){var b=$mjs(c).stop().getTarget();while("a"!=b.tagName.toLowerCase()&&b!=this.t26){b=b.parentNode}
if("a"!=b.tagName.toLowerCase()){return}
switch(b.rel){case"previous":this.restore(this.t18(this,this._o.slideshowLoop));break;case"next":this.restore(this.t17(this,this._o.slideshowLoop));break;case"close":this.restore(null);break}},t11:function(b){b=b||false;var c=$J.doc.j29("bg:t32"),a={},e=0;if(!c){var d=$J.$new("DIV").j2("MagicThumb-background").j6({position:"fixed",display:"block",top:0,bottom:0,left:0,right:0,zIndex:(this._o.zIndex-1),overflow:"hidden",backgroundColor:this._o.backgroundColor,opacity:0,border:0,margin:0,padding:0}).append($J.$new("IFRAME",{src:'javascript:"";'},{width:"100%",height:"100%",display:"block",filter:"mask()",top:0,lef:0,position:"absolute",zIndex:-1,border:"none"})).j32($J.body).hide();$J.doc.j30("bg:t32",c=new $J.FX(d,{transition:$J.FX.Transition.linear,duration:this._o.backgroundSpeed,onStart:function(f){if(f){this.j6($J.extend($J.doc.j12(),{position:"absolute"}))}}.j24(d,this.ieBack),onComplete:function(){this.j23(this.j5("opacity"),true)}.j24(d)}));a={opacity:[0,this._o.backgroundOpacity/100]}}else{c.stop();e=c.el.j5("opacity");c.el.j6Prop("background-color",this._o.backgroundColor);a=(b)?{opacity:[e,0]}:{opacity:[e,this._o.backgroundOpacity/100]};c.options.duration=this._o.backgroundSpeed}
c.el.show();c.start(a)},t13:function(c){c=c||0;var b=$mjs(window).j7(),a=$mjs(window).j10();return{left:a.x+c,right:a.x+b.width-c,top:a.y+c,bottom:a.y+b.height-c}},t14:function(b,c){var a=this.t13(this._o.screenPadding);c=c||a;return{y:Math.max(a.top,Math.min(a.bottom,c.bottom-(c.bottom-c.top-b.height)/2)-b.height),x:Math.max(a.left,Math.min(a.right,c.right-(c.right-c.left-b.width)/2)-b.width)}},resize:function(){var d=$mjs(window).j7(),j=this.t22.j29("size"),e=this.t22.j29("ratio"),c=this.t22.j29("padX"),a=this.t22.j29("padY"),i=this.t22.j29("hspace"),b=this.t22.j29("vspace"),g=0,f=0;if(this.hCaption){g=Math.min(this.i2.width+i,Math.min(j.width,d.width-c-this.scrPad.x)),f=Math.min(this.i2.height+b,Math.min(j.height,d.height-this.scrPad.y))}else{g=Math.min(this.i2.width+i,Math.min(j.width,d.width-this.scrPad.x)),f=Math.min(this.i2.height+b,Math.min(j.height,d.height-a-this.scrPad.y))}
if(g/f>e){g=f*e}else{if(g/f<e){f=g/e}}
this.t22.j6Prop("width",g);if(this.cr){this.cr.j6({top:(this.i2.self.j7().height-this.cr.j7().height)})}
return{width:Math.ceil(g),height:Math.ceil(f)}},adjBorder:function(e,c,a){var d=false;switch($J.j21.engine){case"gecko":d="content-box"!=(e.j5("box-sizing")||e.j5("-moz-box-sizing"));break;case"webkit":d="content-box"!=(e.j5("box-sizing")||e.j5("-webkit-box-sizing"));break;case"trident":d=$J.j21.backCompat||"content-box"!=(e.j5("box-sizing")||e.j5("-ms-box-sizing")||"content-box");break;default:d="content-box"!=e.j5("box-sizing");break}
return(d)?c:c-a},t9:function(d){function b(i){var g=[];if("string"==$J.j1(i)){return i}
for(var f in i){g.push(f.dashize()+":"+i[f])}
return g.join(";")}
var e=$mjs(b(d).split(";")),c=null,a=null;e.forEach(function(g){for(var f in this._o){a=new RegExp("^"+f.dashize().replace(/\-/,"\\-")+"\\s*:\\s*([^;]+)$","i").exec(g.j26());if(a){switch($J.j1(this._o[f])){case"boolean":this._o[f]=a[1].j18();break;case"number":this._o[f]=(a[1].has("."))?(a[1].toFloat()*((f.toLowerCase().has("opacity"))?100:1000)):a[1].j17();break;default:this._o[f]=a[1].j26()}}}},this)},parsePosition:function(){var a=null,c=this.position;for(var b in c){a=new RegExp(""+b+"\\s*:\\s*([^,]+)","i").exec(this._o.expandPosition);if(a){c[b]=(isFinite(c[b]=a[1].j17()))?c[b]:"auto"}}
if((isNaN(c.top)&&isNaN(c.bottom))||(isNaN(c.left)&&isNaN(c.right))){this._o.expandPosition="center"}},t16:function(a){return $mjs(this.thumbs.filter(function(b){return(a==b.id)}))[0]},t15:function(a,b){a=a||null;b=b||false;return $mjs(this.thumbs.filter(function(c){return(a==c.group&&(b||c.ready)&&(b||"uninitialized"!=c.state))}))},t17:function(e,a){a=a||false;var b=this.t15(e.group),d=b.indexOf(e)+1;return(d>=b.length)?(!a)?undefined:b[0]:b[d]},t18:function(e,a){a=a||false;var b=this.t15(e.group),d=b.indexOf(e)-1;return(d<0)?(!a)?undefined:b[b.length-1]:b[d]},t19:function(b){b=b||null;var a=this.t15(b,true);return(a.length)?a[0]:undefined},t20:function(b){b=b||null;var a=this.t15(b,true);return(a.length)?a[a.length-1]:undefined},t21:function(){return $mjs(this.thumbs.filter(function(a){return("expanded"==a.state||"busy-expand"==a.state||"busy-restore"==a.state)}))},onKey:function(b){var a=this._o.slideshowLoop,c=null;if(!this._o.keyboard){$J.doc.je2("keydown");return true}
b=$mjs(b);if(this._o.keyboardCtrl&&!(b.ctrlKey||b.metaKey)){return false}
switch(b.keyCode){case 27:b.stop();this.restore(null);break;case 32:case 34:case 39:case 40:c=this.t17(this,a||32==b.keyCode);break;case 33:case 37:case 38:c=this.t18(this,a);break;default:}
if(c){b.stop();this.restore(c)}}});